### ISSUE TITLE
Original license and copyright notice missing 

### ISSUE THREAD

**Issue by joelittlejohn** [Syncleus/maven-mongodb-plugin#1]
Hi @freemo, you seem to have taken the code and documentation I wrote, stripped out the license and copyright notice and attributed the copyright to your company. This is not okay.

Can you please make sure you're complying with the license here:

https://github.com/joelittlejohn/embedmongo-maven-plugin/blob/master/LICENSE

In particular section 4 ((a) (b) (c) and (d)). If you want to distribute this project publicly, you need to make sure that the original NOTICE and LICENSE remain intact.

I'd be interested to know why you preferred to fork and rename the project instead of simply contributing some changes. Of course you're free to fork the project entirely if you wish, but you must comply with the license. 

Also, I'd appreciate if you could make it clear where this project came from with a note in the README.md and by using GitHub's fork feature to recreate this repo, making it obvious what the origin is.

Cheers

**Comment by freemo** [comment]
The project has been re licensed which is allowed under the apache license, the relevant except is here:

You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

With that said you are correct that your own notice of any copyright should be retained (which is why your name still exists in the contributor section). However it is allowed to replace the old license with a new one as Apache is a permissive license. With that said I will add a section noting that parts of the project were originally licensed under APACHE license. I certainly don't want that credit to be unrecognized. Hopefully you'll find that acceptable, I certainly want your contributions to be credited.

As for why I forked and started this project as a new one is mainly centered around the fact that I need certain features, and development just appeared to be moving too slowly. That and by adding it to my own infrastructure can encourage some of my existing team to help contribute.

I will make sure to add a note to each source file to make it more clear where the project was forked from. I'm not sure if the readme, however, is the best place for that, I also note it in the changelog. As for forking the project on github, that definitely wont be the case as github treats forks in a special way and isnt usually suitable for new projects that will be maintained independently.

Let me know if that sounds more acceptable to you. Ill let you know once those changes have been made.

**Comment by joelittlejohn** [comment]
Thanks for your understanding.

ASL is of course a permissive license, and allows relicensing, but it's quite clear about the need to retain the original copyright notice and the other requirements on creating derivative works. It sounds like you agree that simply replacing the NOTICE/LICENSE is not a valid way to relicense ASL code. You are free to **add** your own copyright notice, of course. Also, I don't agree that the README is a bad place to mention the origin of the project.

I wouldn't have mentioned this but after a lot of thought I felt that the original credit (and copyright) was too lacking to ignore. Please do let me know when you've made some changes. I'm glad this project has been useful for you and I do appreciate your help here.

**Comment by freemo** [comment]
Yes the removal of your copyright notice from header of the source files was unintentionally. That I will add back, and I thank you for pointing it out. I will consider where to best cite the origins of the project. We may keep this in our wiki however, I will let you know. Your name will remain in the contributors list however.

**Comment by freemo** [comment]
I added back your copyrights and attributions. As such I'm closing this ticket. Also keep in mind we dont use github for our tickets but JIRA. So please file future tickets in JIRA. If you need to contact me please feel free to send me an email as well: jeffrey.freeman@syncleus.com
